version: "3.9"

services:
  taskhub:
#    build: .
    image: ali5345/tashhub:latest
    ports:
      - "5000:5000"
    volumes:
      - taskhub_data:/app/data
    environment:
      - TASKHUB_DATA=/app/data/tasks.json
      - PORT=5000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  taskhub_data:
